In [9]:
import pandas as pd 
import numpy as np

In [10]:
data=pd.read_csv(r"E:\SmartClassromAttentionSystem\DataSet\Labels\AllLabels.csv")
data

              ClipID  Boredom  Engagement  Confusion  Frustration
0     1100011002.avi        0           2          0             0
1     1100011003.avi        0           2          0             0
2     1100011004.avi        0           3          0             0
3     1100011005.avi        0           3          0             0
4     1100011006.avi        0           3          0             0
...              ...      ...         ...        ...           ...
8920  9877360164.avi        1           3          0             0
8921  9877360165.avi        0           3          0             0
8922  9877360166.avi        1           3          0             2
8923  9877360168.avi        1           3          1             1
8924  9877360169.avi        0           1          0             0

[8925 rows x 5 columns]

In [11]:
data=data[["ClipID","Engagement"]]
data

              ClipID  Engagement
0     1100011002.avi           2
1     1100011003.avi           2
2     1100011004.avi           3
3     1100011005.avi           3
4     1100011006.avi           3
...              ...         ...
8920  9877360164.avi           3
8921  9877360165.avi           3
8922  9877360166.avi           3
8923  9877360168.avi           3
8924  9877360169.avi           1

[8925 rows x 2 columns]

In [12]:
engagement_mapping={
    0 : "Distracted",
    1 : "Distracted",
    2 : "Attentive",    
    3 : "Attentive"
}

data["Attention"]=data["Engagement"].map(engagement_mapping)
data

              ClipID  Engagement   Attention
0     1100011002.avi           2   Attentive
1     1100011003.avi           2   Attentive
2     1100011004.avi           3   Attentive
3     1100011005.avi           3   Attentive
4     1100011006.avi           3   Attentive
...              ...         ...         ...
8920  9877360164.avi           3   Attentive
8921  9877360165.avi           3   Attentive
8922  9877360166.avi           3   Attentive
8923  9877360168.avi           3   Attentive
8924  9877360169.avi           1  Distracted

[8925 rows x 3 columns]

In [13]:
data.to_csv(r"E:\SmartClassromAttentionSystem\DataSet\Attention_labels.csv")